server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com #eureka服务端实例名称
  client:
    register-with-eureka: false #表示不向注册中心注册自己
    fetch-registry: false #false表示自己就是注册中心，我的职责就是维护服务实例,并不区检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  server:
    # 关闭Eureka的自我保护机制
    enable-self-preservation: false
    # 清理间隔时间（单位毫秒，默认是60*1000）
    eviction-interval-timer-in-ms: 2000