server:
  port: 9999

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/    #服务名称
  instance:
    instance-id: order-feign-9999
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true

# 因为Feign本质上是通过Ribbon来发出请求，因此超时时间也可以通过ribbon来设置，与上面等价
ribbon:
#  读取资源的超时时间
  ReadTimeout: 6000
#  建立连接的超时时间
  ConnectionTimeout: 1000

logging:
  level:
#    feign 日志在哪个接口，什么级别
    com.hruan.springcloud.service.PaymentFeignService: info
